// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrVBPcdEd8MoyPboAeMwzXcbN2rayBsXU',
    appId: '1:24979268019:web:946e94619fd84aa3f86bc6',
    messagingSenderId: '24979268019',
    projectId: 'rideglidefire',
    authDomain: 'rideglidefire.firebaseapp.com',
    storageBucket: 'rideglidefire.appspot.com',
    measurementId: 'G-XCKTTBKJLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCotsBAnkGyoaqppB2t2deVhPmTFsFy28E',
    appId: '1:24979268019:android:d2769756f4638aaef86bc6',
    messagingSenderId: '24979268019',
    projectId: 'rideglidefire',
    storageBucket: 'rideglidefire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-mwWVmMkxm3ABdrExyI1JeChZ3N_NsmI',
    appId: '1:24979268019:ios:0f992549fbde271ef86bc6',
    messagingSenderId: '24979268019',
    projectId: 'rideglidefire',
    storageBucket: 'rideglidefire.appspot.com',
    androidClientId: '24979268019-8gqat656fihrjt7tjet7tgpt5pke2se2.apps.googleusercontent.com',
    iosClientId: '24979268019-sh0n6e24tcskoa1gs22mi9469msb0fjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideGlideDriverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-mwWVmMkxm3ABdrExyI1JeChZ3N_NsmI',
    appId: '1:24979268019:ios:9fbf1decd4c60bb6f86bc6',
    messagingSenderId: '24979268019',
    projectId: 'rideglidefire',
    storageBucket: 'rideglidefire.appspot.com',
    androidClientId: '24979268019-8gqat656fihrjt7tjet7tgpt5pke2se2.apps.googleusercontent.com',
    iosClientId: '24979268019-a5aebolfjniqu2jh4h29lfpt6cjqlrnc.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideGlideDriverApp.RunnerTests',
  );
}
